version: '3.8'

services:
  # Banking Ledger API Service
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - my_network

  processor:
    build:
      context: .
      dockerfile: processor.Dockerfile
    env_file:
      - .env
    networks:
      - my_network

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:

networks:
  my_network:
    driver: bridge