version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: banking_ledger
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking_user -d banking_ledger"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: banking_user
      MONGO_INITDB_ROOT_PASSWORD: banking_password
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: banking_user
      RABBITMQ_DEFAULT_PASS: banking_password
    networks:
      - my_network

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:

networks:
  my_network:
    driver: bridge